#!/usr/bin/env python3
"""Build policy-compliant anonymous review bundle v3.

Starts from the validated deterministic v2 review bundle, replaces the manuscript
with policy-compliant manuscript v3, adds an anonymous AI-assistance disclosure,
and conservatively annotates every submitted Python source file at whole-file
level. Scientific results and empirical runners are not changed or rerun.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import tempfile
import zipfile

from scripts.build_n2_mee_manuscript_v3 import build_manuscript_text as build_v3_text
from scripts.build_n2_mee_review_bundle import FORBIDDEN_IDENTITY_TOKENS, build_bundle as build_v2_bundle


AI_HEADER = "# Generative-AI assistance disclosure: this submitted source file was conservatively\n# annotated at whole-file level because iterative development may include code drafted or\n# revised with OpenAI ChatGPT (GPT-5.6 Sol). Authors reviewed and validated the submitted code.\n"

AI_DISCLOSURE = """# Generative-AI assistance disclosure for peer review

OpenAI ChatGPT (GPT-5.6 Sol) was used during development to assist with language editing, code drafting and revision, test scaffolding, documentation and repository organization. The authors defined the scientific questions, prospective contracts, estimands, frozen decision rules and claim boundaries; executed and validated analyses; inspected outputs and failures; reviewed submitted code and text; and retain responsibility for interpretation and submission.

Development was iterative and exact line-level provenance is not recoverable for all AI-assisted code. To avoid under-disclosure, every Python source file included in this anonymous peer-review archive is therefore conservatively annotated at whole-file level. This annotation does not imply that every line was generated by AI; it records that AI assistance may have contributed to drafting or revision of the file and that the authors are responsible for the submitted implementation.
"""


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _annotate_python(text: str) -> str:
    if "Generative-AI assistance disclosure:" in text:
        return text
    lines = text.splitlines(keepends=True)
    if lines and lines[0].startswith("#!"):
        return lines[0] + AI_HEADER + "".join(lines[1:])
    return AI_HEADER + text


def _scan_identity(stage: Path) -> None:
    violations: list[str] = []
    for path in sorted(p for p in stage.rglob("*") if p.is_file()):
        try:
            text = path.read_text(encoding="utf-8").lower()
        except UnicodeDecodeError:
            continue
        for token in FORBIDDEN_IDENTITY_TOKENS:
            if token in text:
                violations.append(f"{path.relative_to(stage)}: {token}")
    if violations:
        raise ValueError("anonymous bundle contains identity tokens: " + "; ".join(violations))


def _manifest(stage: Path) -> dict[str, object]:
    files = []
    for path in sorted(p for p in stage.rglob("*") if p.is_file()):
        if path.name == "REVIEW_BUNDLE_MANIFEST.json":
            continue
        files.append({
            "path": path.relative_to(stage).as_posix(),
            "sha256": _sha256(path),
            "bytes": path.stat().st_size,
        })
    python_files = [item["path"] for item in files if str(item["path"]).endswith(".py")]
    return {
        "schema_version": 3,
        "bundle_role": "double_anonymous_peer_review_policy_compliant",
        "manuscript_title": "Beyond flat niche maps: separating added-axis thickness from transferable ecological organization",
        "contains_git_history": False,
        "contains_author_identity": False,
        "contains_internal_workflow_or_pr_provenance": False,
        "contains_public_data_dois": True,
        "contains_integrated_manuscript_v3": True,
        "contains_generality_validation": True,
        "contains_archived_data_ethics_statement": True,
        "contains_generative_ai_disclosure": True,
        "python_file_ai_annotation_mode": "whole_file_conservative",
        "python_file_ai_annotation_count": len(python_files),
        "files": files,
    }


def _zip_deterministic(stage: Path, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(p for p in stage.rglob("*") if p.is_file()):
            info = zipfile.ZipInfo(path.relative_to(stage).as_posix())
            info.date_time = (1980, 1, 1, 0, 0, 0)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, path.read_bytes())


def build_bundle(output: Path) -> dict[str, object]:
    with tempfile.TemporaryDirectory(prefix="n2-review-v3-") as temp:
        root = Path(temp)
        base_zip = root / "base.zip"
        build_v2_bundle(base_zip)
        stage = root / "stage"
        stage.mkdir()
        with zipfile.ZipFile(base_zip) as archive:
            archive.extractall(stage)

        old_manuscript = stage / "manuscript" / "N2_MEE_MANUSCRIPT_DRAFT_v2.md"
        if old_manuscript.exists():
            old_manuscript.unlink()
        (stage / "manuscript" / "N2_MEE_MANUSCRIPT_DRAFT_v3.md").write_text(build_v3_text(), encoding="utf-8")
        (stage / "AI_ASSISTANCE_DISCLOSURE.md").write_text(AI_DISCLOSURE, encoding="utf-8")

        readme = (stage / "README_REVIEW.md").read_text(encoding="utf-8")
        readme = readme.replace("integrated manuscript v2", "integrated manuscript v3")
        readme += "\n## Generative-AI disclosure\n\nSee `AI_ASSISTANCE_DISCLOSURE.md`. Python source files are conservatively annotated at whole-file level.\n"
        (stage / "README_REVIEW.md").write_text(readme, encoding="utf-8")

        for path in sorted(stage.rglob("*.py")):
            path.write_text(_annotate_python(path.read_text(encoding="utf-8")), encoding="utf-8")

        manifest_path = stage / "REVIEW_BUNDLE_MANIFEST.json"
        if manifest_path.exists():
            manifest_path.unlink()
        _scan_identity(stage)
        manifest = _manifest(stage)
        manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        _scan_identity(stage)
        _zip_deterministic(stage, output)

    return {
        "output": str(output),
        "sha256": _sha256(output),
        "bytes": output.stat().st_size,
        "file_count": len(manifest["files"]) + 1,
        "python_file_ai_annotation_count": manifest["python_file_ai_annotation_count"],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("dist/N2_MEE_ANONYMOUS_REVIEW_BUNDLE_v3.zip"))
    args = parser.parse_args()
    print(json.dumps(build_bundle(args.output), sort_keys=True))


if __name__ == "__main__":
    main()
