"""Content identity lock for upstream model artifacts used by external validation.

The lock treats local filesystem paths as transport details, not scientific
identity. Scientific identity is the ordered set of (refit_id, artifact_id,
sha256) rows. Every frozen refit must be represented by at least one regular
non-symlink file.

This module verifies artifact identity only. It does not prove that a downstream
score table was actually generated by the frozen artifacts.
"""
from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Mapping, Sequence


MODEL_ARTIFACT_LOCK_ID = "odsp-upstream-model-artifact-lock-v1"
_DECLARATION_FIELDS = {"refit_id", "artifact_id", "path"}
_SNAPSHOT_FIELDS = {"refit_id", "artifact_id", "sha256"}


def _text(value: object, *, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{name} must be non-empty text")
    return value.strip()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _normalized_refit_ids(refit_ids: Sequence[object]) -> tuple[str, ...]:
    rows = tuple(_text(value, name=f"refit_ids[{index}]") for index, value in enumerate(refit_ids))
    if not rows:
        raise ValueError("refit_ids must not be empty")
    if len(rows) != len(set(rows)):
        raise ValueError("refit_ids must be unique")
    return tuple(sorted(rows))


def snapshot_upstream_model_artifacts(
    declarations: Sequence[Mapping[str, object]] | object,
    *,
    base_dir: str | Path,
    refit_ids: Sequence[object],
) -> tuple[dict[str, str], ...]:
    """Hash declared model artifacts into a canonical path-free snapshot."""

    frozen_refits = _normalized_refit_ids(refit_ids)
    frozen_refit_set = set(frozen_refits)
    if not isinstance(declarations, Sequence) or isinstance(
        declarations, (str, bytes, bytearray)
    ):
        raise ValueError("upstream_model_artifacts must be a JSON-array-like sequence")
    if not declarations:
        raise ValueError("upstream_model_artifacts must not be empty")

    root = Path(base_dir)
    rows: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    represented: set[str] = set()

    for index, raw in enumerate(declarations):
        if not isinstance(raw, Mapping):
            raise ValueError(f"upstream_model_artifacts[{index}] must be an object")
        if set(raw) != _DECLARATION_FIELDS:
            raise ValueError(
                f"upstream_model_artifacts[{index}] fields must be exactly "
                "['artifact_id', 'path', 'refit_id']"
            )
        refit_id = _text(raw.get("refit_id"), name=f"upstream_model_artifacts[{index}].refit_id")
        artifact_id = _text(
            raw.get("artifact_id"), name=f"upstream_model_artifacts[{index}].artifact_id"
        )
        raw_path = _text(raw.get("path"), name=f"upstream_model_artifacts[{index}].path")
        if refit_id not in frozen_refit_set:
            raise ValueError(
                f"upstream model artifact references unknown frozen refit {refit_id!r}"
            )
        key = (refit_id, artifact_id)
        if key in seen:
            raise ValueError(
                f"duplicate upstream model artifact logical identity: "
                f"refit_id={refit_id!r}, artifact_id={artifact_id!r}"
            )
        seen.add(key)

        path = Path(raw_path)
        if not path.is_absolute():
            path = root / path
        if path.is_symlink():
            raise ValueError(
                f"upstream model artifact must not be a symlink: "
                f"refit_id={refit_id!r}, artifact_id={artifact_id!r}"
            )
        if not path.exists():
            raise FileNotFoundError(path)
        if not path.is_file():
            raise ValueError(
                f"upstream model artifact must be a regular file: "
                f"refit_id={refit_id!r}, artifact_id={artifact_id!r}"
            )
        represented.add(refit_id)
        rows.append(
            {
                "refit_id": refit_id,
                "artifact_id": artifact_id,
                "sha256": _sha256_file(path),
            }
        )

    missing = sorted(frozen_refit_set - represented)
    if missing:
        raise ValueError(f"missing artifacts for frozen refit(s): {missing!r}")

    rows.sort(key=lambda row: (row["refit_id"], row["artifact_id"]))
    return tuple(rows)


def normalize_upstream_model_artifact_snapshot(
    raw: object,
    *,
    refit_ids: Sequence[object],
) -> tuple[dict[str, str], ...]:
    """Validate a frozen logical-id/content snapshot."""

    frozen_refits = _normalized_refit_ids(refit_ids)
    frozen_refit_set = set(frozen_refits)
    if not isinstance(raw, Sequence) or isinstance(raw, (str, bytes, bytearray)) or not raw:
        raise ValueError("upstream model artifact snapshot must be a non-empty sequence")
    rows: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    represented: set[str] = set()
    for index, item in enumerate(raw):
        if not isinstance(item, Mapping):
            raise ValueError(f"upstream model artifact snapshot[{index}] must be an object")
        if set(item) != _SNAPSHOT_FIELDS:
            raise ValueError(
                f"upstream model artifact snapshot[{index}] fields must be exactly "
                "['artifact_id', 'refit_id', 'sha256']"
            )
        refit_id = _text(item.get("refit_id"), name=f"snapshot[{index}].refit_id")
        artifact_id = _text(item.get("artifact_id"), name=f"snapshot[{index}].artifact_id")
        digest = _text(item.get("sha256"), name=f"snapshot[{index}].sha256")
        if refit_id not in frozen_refit_set:
            raise ValueError(
                f"upstream model artifact snapshot references unknown frozen refit {refit_id!r}"
            )
        if len(digest) != 64 or digest.lower() != digest:
            raise ValueError(f"snapshot[{index}].sha256 must be lowercase SHA256 text")
        try:
            int(digest, 16)
        except ValueError as exc:
            raise ValueError(
                f"snapshot[{index}].sha256 must be lowercase SHA256 text"
            ) from exc
        key = (refit_id, artifact_id)
        if key in seen:
            raise ValueError(
                f"duplicate upstream model artifact snapshot identity: "
                f"refit_id={refit_id!r}, artifact_id={artifact_id!r}"
            )
        seen.add(key)
        represented.add(refit_id)
        rows.append(
            {"refit_id": refit_id, "artifact_id": artifact_id, "sha256": digest}
        )

    expected_order = sorted(rows, key=lambda row: (row["refit_id"], row["artifact_id"]))
    if rows != expected_order:
        raise ValueError(
            "upstream model artifact snapshot must be sorted by refit_id, artifact_id"
        )
    missing = sorted(frozen_refit_set - represented)
    if missing:
        raise ValueError(
            f"upstream model artifact snapshot missing frozen refit(s): {missing!r}"
        )
    return tuple(rows)


def verify_upstream_model_artifact_snapshot(
    frozen_snapshot: object,
    declarations: Sequence[Mapping[str, object]] | object,
    *,
    base_dir: str | Path,
    refit_ids: Sequence[object],
) -> tuple[dict[str, str], ...]:
    """Rehash runtime artifacts and require exact logical-id/content equality."""

    frozen = normalize_upstream_model_artifact_snapshot(
        frozen_snapshot, refit_ids=refit_ids
    )
    current = snapshot_upstream_model_artifacts(
        declarations, base_dir=base_dir, refit_ids=refit_ids
    )
    if current != frozen:
        raise ValueError(
            "upstream model artifact snapshot mismatch: "
            f"frozen={list(frozen)!r}, runtime={list(current)!r}"
        )
    return current
